# Generated by Django 5.2.9 on 2025-12-09 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Promotor(a) Blitz', max_length=200)),
                ('local', models.CharField(help_text='Ex: Rodovia Hélio Smidt - Guarulhos/SP', max_length=200)),
                ('descricao', models.TextField(help_text='Descrição geral do trabalho')),
                ('uniforme', models.TextField(default='Calça preta e tênis branco', help_text='O que precisa vestir')),
                ('infos_extras', models.TextField(blank=True, help_text='Alimentação, Transporte, etc.')),
                ('data_pagamento', models.DateField(help_text='Quando o cachê cai?')),
                ('status', models.CharField(choices=[('aberto', 'Casting Aberto'), ('analise', 'Em Análise'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor deste dia específico', max_digits=8)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Ex: 1.75', max_digits=3)),
                ('manequim', models.CharField(help_text='Ex: 38, 40', max_length=10)),
                ('calcado', models.CharField(help_text='Ex: 37, 39', max_length=10)),
                ('foto_rosto', models.ImageField(blank=True, upload_to='modelos/rosto/')),
                ('foto_corpo', models.ImageField(blank=True, upload_to='modelos/corpo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Aprovação'), ('aprovado', 'Aprovado ✅'), ('reprovado', 'Não selecionado ❌')], default='pendente', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'unique_together': {('job', 'modelo')},
            },
        ),
    ]
