# Generated by Django 5.2.9 on 2025-12-09 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: Possui veículo próprio?', max_length=200)),
                ('tipo', models.CharField(choices=[('texto', 'Texto Curto'), ('sim_nao', 'Sim ou Não')], default='sim_nao', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='data_pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='infos_extras',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='local',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='uniforme',
            field=models.TextField(default='Calça preta e tênis branco'),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='altura',
            field=models.DecimalField(decimal_places=2, help_text='Ex: 1.70', max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calcado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_corpo',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/corpo/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_rosto',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/rosto/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manequim',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pergunta')),
            ],
        ),
    ]
