# Generated by Django 5.2.9 on 2025-12-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_bairro_userprofile_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Cadastro Aprovado?'),
        ),
    ]
