# Generated by Django 5.2.9 on 2025-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='motivo_reprovacao',
            field=models.CharField(blank=True, choices=[('fotos_ruins', 'Fotos fora do padrão (Escuras/Selfie/Espelho)'), ('dados_incompletos', 'Dados incompletos ou incorretos'), ('perfil', 'Perfil não compatível no momento'), ('outros', 'Outros (Ver observação)')], max_length=50, null=True, verbose_name='Motivo (Se reprovado)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='observacao_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem para a Modelo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado'), ('reprovado', '🔴 Reprovado')], default='pendente', max_length=20),
        ),
    ]
