# Generated by Django 5.2.9 on 2025-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_agencia_userprofile_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=20, null=True, verbose_name='Tipo de Conta'),
        ),
    ]
