# Generated by Django 5.2.9 on 2025-12-13 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='candidatura',
            options={'verbose_name': 'Candidatura', 'verbose_name_plural': '📝 Candidaturas Recebidas'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Vaga / Job', 'verbose_name_plural': '💼 Vagas e Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobdia',
            options={'verbose_name': 'Dia de Trabalho', 'verbose_name_plural': 'Dias e Cachês'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name': 'Pergunta do Formulário', 'verbose_name_plural': '⚙️ Perguntas do Cadastro'},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Promotor / Talento', 'verbose_name_plural': '📂 Base de Promotores'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ex: @seu.perfil', max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='termo_comunicacao',
            field=models.BooleanField(default=False, help_text='Autoriza contato via WhatsApp/E-mail sobre vagas.', verbose_name='Aceito receber comunicações'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='termo_uso_imagem',
            field=models.BooleanField(default=False, help_text='Autoriza o uso de fotos e vídeos para divulgação.', verbose_name='Aceito o uso de imagem'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cliente_nome',
            field=models.CharField(max_length=100, verbose_name='Empresa/Cliente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(verbose_name='Opinião'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='data_candidatura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='Candidato'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando Análise'), ('aprovado', '✅ Selecionado para o Job'), ('reprovado', '❌ Não Selecionado')], default='pendente', help_text="Se 'Selecionado', o promotor verá a confirmação no painel dele.", max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='job',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='job',
            name='data_pagamento',
            field=models.DateField(verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='job',
            name='descricao',
            field=models.TextField(help_text='Descreva as funções e o perfil desejado.', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='job',
            name='infos_extras',
            field=models.TextField(blank=True, help_text='Instruções adicionais (horário de chegada, etc).', verbose_name='Infos Extras'),
        ),
        migrations.AlterField(
            model_name='job',
            name='local',
            field=models.CharField(help_text='Cidade, Bairro ou Endereço principal', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('aberto', 'Casting Aberto'), ('analise', 'Em Análise (Fechado)'), ('finalizado', 'Finalizado')], default='aberto', help_text='<b>Aberto:</b> Visível para todos os promotores.<br><b>Em Análise:</b> Ninguém mais pode se candidatar.<br><b>Finalizado:</b> Evento concluído.', max_length=20, verbose_name='Status da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(help_text='Ex: Promotor para Blitz Dr. Peanut', max_length=200, verbose_name='Título da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='uniforme',
            field=models.TextField(default='Calça preta e tênis branco', verbose_name='Uniforme'),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='data',
            field=models.DateField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='hora_fim',
            field=models.TimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cachê (R$)'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa no Cadastro?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=200, verbose_name='Pergunta'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto Curto'), ('sim_nao', 'Sim ou Não')], default='sim_nao', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto_resposta',
            field=models.CharField(max_length=200, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exemplo: 1.70', max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calcado',
            field=models.CharField(blank=True, help_text='Ex: 36, 37, 40...', max_length=10, null=True, verbose_name='Calçado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta e Dígito'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_corpo',
            field=models.ImageField(blank=True, help_text='Foto para avaliação de perfil completo.', null=True, upload_to='modelos/corpo/', verbose_name='Foto de Corpo Inteiro'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_rosto',
            field=models.ImageField(blank=True, help_text='Esta foto será usada na carteirinha digital e nas miniaturas.', null=True, upload_to='modelos/rosto/', verbose_name='Foto de Rosto (Close)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manequim',
            field=models.CharField(blank=True, help_text='Ex: P, M, G, 38, 40...', max_length=10, null=True, verbose_name='Manequim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivo_reprovacao',
            field=models.CharField(blank=True, choices=[('fotos_ruins', 'Fotos fora do padrão (Escuras/Selfie/Espelho)'), ('dados_incompletos', 'Dados incompletos ou incorretos'), ('perfil', 'Perfil não compatível no momento'), ('outros', 'Outros (Ver observação)')], help_text='Selecione um motivo apenas se estiver reprovando o cadastro.', max_length=50, null=True, verbose_name='Motivo da Reprovação'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nome_completo',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='observacao_admin',
            field=models.TextField(blank=True, help_text='Escreva aqui o que o promotor precisa corrigir. Essa mensagem será enviada por e-mail.', null=True, verbose_name='Mensagem para o Promotor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado (Liberado)'), ('reprovado', '🔴 Reprovado (Bloqueado)')], default='pendente', help_text="ℹ️ <b>IMPORTANTE:</b> Se você marcar como 'Aprovado', o promotor receberá um e-mail de boas-vindas e poderá ver as vagas no site.", max_length=20, verbose_name='Situação do Cadastro'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20, null=True, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Vínculo com o login (e-mail e senha) do sistema.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Conta de Acesso'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único usado para gerar os links de compartilhamento.', unique=True, verbose_name='ID Público'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(help_text='Formato: (11) 99999-9999', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
