# Generated by Django 5.2.9 on 2025-12-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_avaliacao_options_alter_candidatura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='areas_atuacao',
            field=models.TextField(blank=True, null=True, verbose_name='Áreas de Interesse'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cabelo_comprimento',
            field=models.CharField(blank=True, choices=[('curto', 'Curto'), ('medio', 'Médio'), ('longo', 'Longo'), ('careca', 'Careca/Raspado')], max_length=20, null=True, verbose_name='Comprimento do Cabelo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cabelo_tipo',
            field=models.CharField(blank=True, choices=[('liso', 'Liso'), ('ondulado', 'Ondulado'), ('cacheado', 'Cacheado'), ('crespo', 'Crespo'), ('black_power', 'Black Power'), ('dread', 'Dreadlocks'), ('trancas', 'Tranças')], max_length=20, null=True, verbose_name='Tipo de Cabelo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='descricao_pcd',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual deficiência? (Se PCD)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponibilidade',
            field=models.CharField(blank=True, choices=[('total', 'Todos os dias (Incluindo Finais de Semana)'), ('seg_sex', 'Segunda a Sexta'), ('fds', 'Somente Finais de Semana'), ('noite', 'Somente Período Noturno'), ('freelancer', 'Dias Aleatórios / Sem data fixa')], max_length=20, null=True, verbose_name='Disponibilidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='etnia',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela (Asiáticos/Orientais)'), ('indigena', 'Indígena'), ('outra', 'Outra')], max_length=20, null=True, verbose_name='Cor/Etnia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiencia',
            field=models.CharField(choices=[('sem_experiencia', 'Não tenho experiência (Começando agora)'), ('pouca', 'Tenho, mas pouca'), ('media', 'Tenho experiência'), ('muita', 'Sim, há bastante tempo (Expert)')], default='sem_experiencia', max_length=20, verbose_name='Experiência'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao_binario', 'Não-binário'), ('outros', 'Outros'), ('prefiro_nao_dizer', 'Prefiro não dizer')], max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pcd',
            field=models.BooleanField(default=False, verbose_name='É PCD (Pessoa com Deficiência)?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nacionalidade',
            field=models.CharField(choices=[('brasileira', 'Brasileira 🇧🇷'), ('americana', 'Americana 🇺🇸'), ('espanhola', 'Espanhola 🇪🇸'), ('francesa', 'Francesa 🇫🇷'), ('italiana', 'Italiana 🇮🇹'), ('japonesa', 'Japonesa 🇯🇵'), ('chinesa', 'Chinesa 🇨🇳'), ('alemama', 'Alemã 🇩🇪'), ('outra', 'Outra')], default='brasileira', max_length=20, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_espanhol',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('fluente', 'Fluente/Nativo')], max_length=15, null=True, verbose_name='Espanhol'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_frances',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('fluente', 'Fluente/Nativo')], max_length=15, null=True, verbose_name='Francês'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_ingles',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('fluente', 'Fluente/Nativo')], max_length=15, null=True, verbose_name='Inglês'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='olhos',
            field=models.CharField(blank=True, choices=[('castanho_escuro', 'Castanho Escuro'), ('castanho_claro', 'Castanho Claro'), ('azul', 'Azul'), ('verde', 'Verde'), ('mel', 'Mel'), ('preto', 'Preto'), ('heterocromia', 'Heterocromia')], max_length=20, null=True, verbose_name='Cor dos Olhos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outros_idiomas',
            field=models.CharField(blank=True, help_text='Ex: Japonês Fluente, Alemão Básico', max_length=200, null=True, verbose_name='Outros Idiomas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / RNE'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tamanho_camiseta',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, null=True, verbose_name='Tamanho de Camiseta'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 1.70', max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Banco'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calcado',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Calçado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_corpo',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/corpo/', verbose_name='Foto de Corpo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_rosto',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/rosto/', verbose_name='Foto de Rosto'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ex: @seu.perfil', max_length=50, null=True, verbose_name='Instagram (Opcional)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manequim',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Manequim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivo_reprovacao',
            field=models.CharField(blank=True, choices=[('fotos_ruins', 'Fotos fora do padrão (Escuras/Selfie/Espelho)'), ('dados_incompletos', 'Dados incompletos ou incorretos'), ('perfil', 'Perfil não compatível no momento'), ('outros', 'Outros (Ver observação)')], max_length=50, null=True, verbose_name='Motivo (Se reprovado)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='observacao_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem para a Modelo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado'), ('reprovado', '🔴 Reprovado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='termo_comunicacao',
            field=models.BooleanField(default=False, verbose_name='Aceito receber comunicações'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='termo_uso_imagem',
            field=models.BooleanField(default=False, verbose_name='Aceito uso de imagem'),
        ),
    ]
