# Generated by Django 5.2.9 on 2025-12-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_areas_atuacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='OpenCasting', max_length=100, verbose_name='Nome do Site')),
                ('email_contato', models.EmailField(default='suporte@opencasting.com', max_length=254, verbose_name='E-mail de Suporte')),
                ('telefone_contato', models.CharField(default='(11) 99999-9999', max_length=20, verbose_name='Telefone / WhatsApp')),
                ('texto_sobre_curto', models.TextField(default='A plataforma líder em gestão de talentos.', help_text='Aquele texto curto que fica na primeira coluna do rodapé.', verbose_name='Resumo (Rodapé)')),
                ('titulo_quem_somos', models.CharField(default='Quem Somos', max_length=50, verbose_name='Título Coluna Extra')),
                ('texto_quem_somos', models.TextField(default='Somos apaixonados por conectar marcas e pessoas.', help_text='Texto completo da nova coluna.', verbose_name='Texto Quem Somos')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Link do Instagram')),
            ],
            options={
                'verbose_name': '⚙️ Configuração do Site',
                'verbose_name_plural': '⚙️ Configurações do Site',
            },
        ),
    ]
