# Generated by Django 5.2.9 on 2025-12-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado'), ('reprovado', '🔴 Reprovado (Banido)'), ('correcao', '🟠 Aguardando Correção'), ('bloqueado', '⛔ Bloqueado Temporariamente')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
