# Generated by Django 5.2.9 on 2025-12-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_bloqueado_ate_alter_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bloqueado_ate',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado'), ('reprovado', '🔴 Reprovado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
