# Generated by Django 5.2.9 on 2025-12-19 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_userprofile_bloqueado_ate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosite',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='telefone_contato',
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='texto_quem_somos',
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='texto_sobre_curto',
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='titulo_quem_somos',
        ),
        migrations.RemoveField(
            model_name='job',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='job',
            name='infos_extras',
        ),
        migrations.RemoveField(
            model_name='job',
            name='uniforme',
        ),
        migrations.RemoveField(
            model_name='jobdia',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='jobdia',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='data_reprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Reprovação'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='data_candidatura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(default='pendente', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='job',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='job',
            name='local',
            field=models.CharField(max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('aberto', 'Casting Aberto'), ('analise', 'Em Análise (Fechado)'), ('finalizado', 'Finalizado')], default='aberto', max_length=20, verbose_name='Status da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título da Vaga'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='observacao_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem Interna / Observação CRM'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pendente', '🟡 Pendente (Em Análise)'), ('aprovado', '🟢 Aprovado'), ('reprovado', '🔴 Reprovado (Bloqueado)'), ('correcao', '🔵 Necessita Ajuste')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
