# Generated by Django 5.2.9 on 2025-12-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_configuracaosite_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidatura',
            options={},
        ),
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobdia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='job',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='job',
            name='local',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='titulo_site',
            field=models.CharField(default='OpenCasting', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobdia',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto_resposta',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='observacao_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem para a Modelo'),
        ),
    ]
