# Generated by Django 5.2.9 on 2025-12-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_avaliacao_options_alter_candidatura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='email_contato',
            field=models.EmailField(default='suporte@opencasting.com', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='job',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('aberto', 'Casting Aberto'), ('analise', 'Em Análise'), ('finalizado', 'Finalizado')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título da Vaga'),
        ),
    ]
