# Generated by Django 5.2.9 on 2025-12-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracaosite_email_contato_job_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(help_text='Formato: (11) 99999-9999', max_length=20, verbose_name='Telefone (WhatsApp)'),
        ),
    ]
