# Generated by Django 5.2.9 on 2025-12-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cpfbanido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpfbanido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motivo_reprovacao',
            field=models.CharField(blank=True, choices=[('fotos_ruins', 'Fotos fora do padrão (Escuras/Selfie/Espelho)'), ('dados_incompletos', 'Dados incompletos ou incorretos'), ('documentos', 'Documentos/Informações ilegíveis ou inconsistentes'), ('menor_idade', 'Menor de idade / inconsistência de idade'), ('perfil', 'Perfil não compatível no momento'), ('outros', 'Outros (Ver observação)')], max_length=50, null=True, verbose_name='Motivo (Se reprovado)'),
        ),
    ]
