# Generated by Django 5.2.9 on 2025-12-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cpfbanido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='endereco_contato',
            field=models.CharField(blank=True, default='Alphaville, Barueri - SP', max_length=120, null=True, verbose_name='Endereço (Rodapé)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='telefone_contato',
            field=models.CharField(blank=True, default='(11) 99999-9999', max_length=30, null=True, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='texto_privacidade',
            field=models.TextField(blank=True, default='Nós respeitamos sua privacidade. Utilizamos os dados cadastrados apenas para fins de seleção, contato e gestão de oportunidades.\n\nVocê pode solicitar atualização ou exclusão dos seus dados entrando em contato pelos canais oficiais da agência.', null=True, verbose_name='Texto - Privacidade'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='texto_quem_somos',
            field=models.TextField(blank=True, default='A OpenCasting é uma agência focada em conectar marcas e talentos com agilidade e transparência.\n\nTrabalhamos com uma base de profissionais verificados para eventos, ações promocionais e ativações de marca.\n\nNossa missão é simplificar a seleção e elevar o padrão de entrega em campo.', null=True, verbose_name='Texto - Quem Somos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='texto_servicos',
            field=models.TextField(blank=True, default='Oferecemos soluções completas para seleção e gestão de equipes para eventos.\n\n• Casting e recrutamento\n• Triagem e aprovação de talentos\n• Gestão de disponibilidade\n• Acompanhamento e avaliações\n', null=True, verbose_name='Texto - Serviços'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='texto_sobre_curto',
            field=models.TextField(blank=True, default='Conectamos as melhores marcas aos profissionais mais qualificados.', help_text='Texto curto que aparece no rodapé/coluna institucional.', null=True, verbose_name='Resumo (Rodapé)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_privacidade',
            field=models.CharField(default='Privacidade', max_length=60, verbose_name='Título - Privacidade'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_quem_somos',
            field=models.CharField(default='Quem Somos', max_length=60, verbose_name='Título - Quem Somos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_servicos',
            field=models.CharField(default='Serviços', max_length=60, verbose_name='Título - Serviços'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='email_contato',
            field=models.EmailField(default='contato@opencasting.com.br', max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='titulo_site',
            field=models.CharField(default='OpenCasting', max_length=100, verbose_name='Nome do Site'),
        ),
    ]
