# Generated by Django 5.2.9 on 2025-12-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_configuracaosite_endereco_contato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='jobdia',
            options={'verbose_name': 'Dia do Trabalho', 'verbose_name_plural': 'Dias do Trabalho'},
        ),
        migrations.AddField(
            model_name='job',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='job',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='job',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='job',
            name='competencias',
            field=models.TextField(blank=True, null=True, verbose_name='Competências'),
        ),
        migrations.AddField(
            model_name='job',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de pagamento'),
        ),
        migrations.AddField(
            model_name='job',
            name='empresa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='job',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='job',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='job',
            name='etnias_aceitas',
            field=models.TextField(blank=True, null=True, verbose_name='Cor/Etnia (aceitas)'),
        ),
        migrations.AddField(
            model_name='job',
            name='generos_aceitos',
            field=models.TextField(blank=True, null=True, verbose_name='Sexo/Gênero (aceitos)'),
        ),
        migrations.AddField(
            model_name='job',
            name='geocodificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geocodificado em'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='job',
            name='nivel_ingles_min',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('fluente', 'Fluente/Nativo')], max_length=15, null=True, verbose_name='Inglês mínimo'),
        ),
        migrations.AddField(
            model_name='job',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='job',
            name='requer_experiencia',
            field=models.BooleanField(default=False, verbose_name='Precisa de experiência?'),
        ),
        migrations.AddField(
            model_name='job',
            name='tipo_servico',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='job',
            name='uniforme',
            field=models.TextField(blank=True, null=True, verbose_name='Uniforme (opcional)'),
        ),
        migrations.AddField(
            model_name='jobdia',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fim'),
        ),
        migrations.AddField(
            model_name='jobdia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora início'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='job',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (opcional)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='local',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local (legado)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título do Trabalho'),
        ),
    ]
