# Generated by Django 5.2.9 on 2025-12-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_job_options_alter_jobdia_options_job_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cabelo_comprimentos_aceitos',
            field=models.TextField(blank=True, null=True, verbose_name='Comprimento do cabelo (aceitos)'),
        ),
        migrations.AddField(
            model_name='job',
            name='cabelo_tipos_aceitos',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo de cabelo (aceitos)'),
        ),
        migrations.AddField(
            model_name='job',
            name='olhos_aceitos',
            field=models.TextField(blank=True, null=True, verbose_name='Cor dos olhos (aceitas)'),
        ),
        migrations.AddField(
            model_name='job',
            name='tipo_servico_outros',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Outros (descrever)'),
        ),
        migrations.AddField(
            model_name='job',
            name='uniforme_fornecido',
            field=models.BooleanField(default=False, verbose_name='Uniforme fornecido pela empresa?'),
        ),
        migrations.AlterField(
            model_name='job',
            name='uniforme',
            field=models.TextField(blank=True, null=True, verbose_name='Uniforme (legado)'),
        ),
    ]
