# Generated by Django 5.2.9 on 2025-12-28

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    ConfiguracaoSite = apps.get_model('core', 'ConfiguracaoSite')
    ContatoSite = apps.get_model('core', 'ContatoSite')

    config, _created = ConfiguracaoSite.objects.get_or_create(pk=1)

    def ensure(tipo, valor, telefone_tipo=None, ordem=0):
        if not valor:
            return
        valor = str(valor).strip()
        if not valor:
            return
        defaults = {'ordem': ordem}
        if telefone_tipo is not None:
            defaults['telefone_tipo'] = telefone_tipo
        ContatoSite.objects.get_or_create(
            configuracao=config,
            tipo=tipo,
            valor=valor,
            defaults=defaults,
        )

    ensure('email', getattr(config, 'email_contato', ''), ordem=0)
    ensure('telefone', getattr(config, 'telefone_contato', ''), telefone_tipo='ambos', ordem=1)
    ensure('instagram', getattr(config, 'instagram_link', ''), ordem=2)


def backwards(apps, schema_editor):
    # Mantém dados (não remove automaticamente)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_job_cabelo_comprimentos_aceitos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('telefone', 'Telefone'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('telefone_tipo', models.CharField(blank=True, choices=[('telefone', 'Somente telefone'), ('whatsapp', 'Somente WhatsApp'), ('ambos', 'Telefone e WhatsApp')], help_text='Usado apenas quando o tipo for Telefone.', max_length=20, null=True, verbose_name='Tipo do número')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.configuracaosite', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
