# Generated by Django 5.2.9 on 2025-12-28

import uuid
from datetime import timedelta

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def default_expira_em():
    return timezone.now() + timedelta(days=7)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contatosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(default=default_expira_em, verbose_name='Expira em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apresentacoes_criadas', to='auth.user', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
            },
        ),
        migrations.CreateModel(
            name='ApresentacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.apresentacao')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Item da apresentação',
                'verbose_name_plural': 'Itens da apresentação',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
