# Generated by Django 5.2.9 on 2025-12-31 19:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rebrand_casting_certo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome fantasia')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura')),
                ('situacao_cadastral', models.CharField(blank=True, max_length=80, null=True, verbose_name='Situação cadastral')),
                ('natureza_juridica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Natureza jurídica')),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE principal')),
                ('cnae_principal_descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do CNAE')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=40, null=True, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=40, null=True, verbose_name='Inscrição municipal')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real'), ('mei', 'MEI'), ('outro', 'Outro/Não informado')], default='outro', max_length=20, verbose_name='Regime tributário')),
                ('email_nfe', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para NF')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=120, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=80, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('contato_nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Contato (nome)')),
                ('contato_cargo', models.CharField(blank=True, max_length=120, null=True, verbose_name='Contato (cargo)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('razao_social', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='configuracaosite',
            options={'verbose_name': 'Contatos', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='expira_em',
            field=models.DateTimeField(default=core.models._apresentacao_default_expira_em, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='texto_quem_somos',
            field=models.TextField(blank=True, default='A Casting Certo é uma agência focada em conectar marcas e talentos com agilidade e transparência.\n\nTrabalhamos com uma base de profissionais verificados para eventos, ações promocionais e ativações de marca.\n\nNossa missão é simplificar a seleção e elevar o padrão de entrega em campo.', null=True, verbose_name='Texto - Quem Somos'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='titulo_site',
            field=models.CharField(default='Casting Certo', max_length=100, verbose_name='Nome do Site'),
        ),
    ]
