# Generated by Django 5.2.9 on 2025-12-31 20:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade_dias', models.PositiveIntegerField(default=30, verbose_name='Orçamento válido por (dias)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='core.cliente', verbose_name='Cliente (opcional)')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=120, verbose_name='Função')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('carga_horaria_horas', models.PositiveIntegerField(default=8, verbose_name='Carga horária (h)')),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da diária (R$)')),
                ('diarias', models.PositiveIntegerField(default=1, verbose_name='Diárias')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (R$)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item do orçamento',
                'verbose_name_plural': 'Itens do orçamento',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
