# Generated by Django 5.2.9 on 2025-12-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_orcamento_orcamentoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do evento'),
        ),
    ]
