# Generated by Django 5.2.9 on 2026-01-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_orcamento_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotorApresentacao',
            fields=[
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentação',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userprofile',),
        ),
    ]
