# Generated by Django 5.2.9 on 2026-03-22 18:50

from django.db import migrations, models


def fix_alemama_data(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(nacionalidade='alemama').update(nacionalidade='alema')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_orcamento_desconto'),
    ]

    operations = [
        migrations.RunPython(fix_alemama_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='nacionalidade',
            field=models.CharField(choices=[('brasileira', 'Brasileira 🇧🇷'), ('americana', 'Americana 🇺🇸'), ('espanhola', 'Espanhola 🇪🇸'), ('francesa', 'Francesa 🇫🇷'), ('italiana', 'Italiana 🇮🇹'), ('japonesa', 'Japonesa 🇯🇵'), ('chinesa', 'Chinesa 🇨🇳'), ('alema', 'Alemã 🇩🇪'), ('outra', 'Outra')], default='brasileira', max_length=20, verbose_name='Nacionalidade'),
        ),
    ]
