"""
Django settings for opencasting project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6m(y3p$s-1znl*o$i$x$&pvqsin-+cjuym2-2wyri8f-9&j%j_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'core',   # <--- TEM QUE TER ESSA LINHA
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'opencasting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opencasting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- CONFIGURAÇÕES REGIONAIS (BRASIL) ---

# Idioma padrão (Muda o Admin para Português)
LANGUAGE_CODE = 'pt-br'

# Fuso Horário (Para os horários ficarem certos no Brasil)
TIME_ZONE = 'America/Sao_Paulo'

# Ativa a tradução
USE_I18N = True

# Ativa a formatação local (Datas: 31/12/2025, Moeda: 1.000,00)
USE_L10N = True

# Fuso horário no banco de dados
USE_TZ = True
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Quando fizer logout, volta para a tela inicial (Landing Page)
LOGOUT_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = 'lista_vagas'
LOGIN_URL = 'login'

# --- CONFIGURAÇÃO DO PAINEL ADMIN (JAZZMIN) ---
JAZZMIN_SETTINGS = {
    "site_title": "OpenCasting Admin",
    "site_header": "OpenCasting",
    "site_brand": "OpenCasting",
    "welcome_sign": "Bem-vindo ao Painel de Controle",
    "copyright": "OpenCasting Agency",
    "search_model": ["core.UserProfile", "core.Job"],
    
    # Menu lateral
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Ícones para deixar intuitivo (Google Icons)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.UserProfile": "fas fa-id-card-alt", # Ícone de crachá para Modelos
        "core.Job": "fas fa-briefcase",             # Ícone de maleta para Vagas
        "core.Candidatura": "fas fa-hand-paper",    # Ícone de mão levantada
        "core.Pergunta": "fas fa-question-circle",
    },
}

# Cores e Estilo (Tema moderno e limpo)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal", # Verde da marca
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal", # Menu lateral escuro com detalhes verdes
    "sidebar_nav_small_text": False,
    "theme": "flatly", # Tema clean e moderno (sem cara de Windows XP)
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}